name: validus
description: Sample stocks app

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.1
  chopper: ^4.0.4
  logging: ^1.0.2
  json_annotation: ^4.4.0
  equatable: ^2.0.3
#  provider: ^6.0.2
  intl: ^0.17.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  chopper_generator: ^4.0.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

